### ISSUE TITLE
Gaspi_Barrier, Timeout and state vector issue

### ISSUE THREAD

**Issue by dhinf** [cc-hpc-itwm/GPI-2#48] opened 2018-11-09 15:42 UTC
As pointed out in issue #30 a barrier running in a time out, still doesn't update the state vector at all. 
Example application:
[state_vec.cpp.txt](https://github.com/cc-hpc-itwm/GPI-2/files/2566453/state_vec.cpp.txt)

output for 8 processes:
time out
0 -> healthy
1 -> healthy
2 -> healthy
3 -> healthy
4 -> healthy
5 -> healthy
6 -> healthy
7 -> healthy

Normally rank 1 shouldn't be healthy.

**Comment by rumach** [comment] 2018-11-12 23:07
Duplicate of #30.

**Closed by rumach** 2018-11-12 23:07 UTC
